use serde::Deserialize;
use std::fmt::Write;

#[derive(Debug, Deserialize)]
pub struct TableDef {
    pub name: String,
    pub columns: Vec<ColumnDef>,
}

#[derive(Debug, Deserialize)]
pub struct ColumnDef {
    pub name: String,
    pub data_type: String,
    pub is_nullable: bool,
    pub has_default: bool,
}

pub fn pg_type_to_ts(pg_type: &str) -> &str {
    match pg_type {
        "Uuid" | "Text" => "string",
        "Int4" | "Int8" | "Float8" | "Numeric" | "Serial" | "BigSerial" => "number",
        "Bool" => "boolean",
        "Timestamp" | "Timestamptz" | "Date" => "string",
        "Jsonb" | "Json" => "unknown",
        "Bytea" => "Uint8Array",
        _ => "unknown",
    }
}

pub fn generate_types(tables: &[TableDef]) -> String {
    let mut output = String::new();
    writeln!(output, "// Auto-generated by garance gen types --lang ts").unwrap();
    writeln!(output, "// Do not edit manually.\n").unwrap();

    for table in tables {
        let type_name = to_pascal_case(&table.name);

        writeln!(output, "export interface {} {{", type_name).unwrap();
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.data_type);
            let nullable = if col.is_nullable { " | null" } else { "" };
            writeln!(output, "  {}: {}{};", col.name, ts_type, nullable).unwrap();
        }
        writeln!(output, "}}\n").unwrap();

        writeln!(output, "export interface {}Insert {{", type_name).unwrap();
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.data_type);
            let optional = if col.has_default || col.is_nullable { "?" } else { "" };
            let nullable = if col.is_nullable { " | null" } else { "" };
            writeln!(output, "  {}{}: {}{};", col.name, optional, ts_type, nullable).unwrap();
        }
        writeln!(output, "}}\n").unwrap();

        writeln!(output, "export interface {}Update {{", type_name).unwrap();
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.data_type);
            let nullable = if col.is_nullable { " | null" } else { "" };
            writeln!(output, "  {}?: {}{};", col.name, ts_type, nullable).unwrap();
        }
        writeln!(output, "}}\n").unwrap();
    }

    output
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}
