// cli/internal/compose/template.go
package compose

func DevComposeTemplate() string {
	return `# Generated by garance dev — do not edit manually
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-garance}
    volumes:
      - garance_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "${S3_PORT:-9000}:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    volumes:
      - garance_storage:/data

  engine:
    image: ghcr.io/garancehq/engine:latest
    ports:
      - "4000:4000"
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-garance}
      LISTEN_ADDR: 0.0.0.0:4000
      GRPC_ADDR: 0.0.0.0:5000

  auth:
    image: ghcr.io/garancehq/auth:latest
    ports:
      - "4001:4001"
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-garance}
      LISTEN_ADDR: 0.0.0.0:4001
      GRPC_ADDR: 0.0.0.0:5001
      JWT_SECRET: ${JWT_SECRET:-dev-secret-change-me}

  storage:
    image: ghcr.io/garancehq/storage:latest
    ports:
      - "4002:4002"
      - "5002:5002"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-garance}
      LISTEN_ADDR: 0.0.0.0:4002
      GRPC_ADDR: 0.0.0.0:5002
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-change-me}

  gateway:
    image: ghcr.io/garancehq/gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - engine
      - auth
      - storage
    environment:
      LISTEN_ADDR: 0.0.0.0:8080
      ENGINE_GRPC_ADDR: engine:5000
      AUTH_GRPC_ADDR: auth:5001
      STORAGE_GRPC_ADDR: storage:5002
      JWT_SECRET: ${JWT_SECRET:-dev-secret-change-me}
      ALLOWED_ORIGINS: "*"

volumes:
  garance_data:
  garance_storage:
`
}
